#Info endpoints
info:
  company: Dexcom
  project: integrations
  kafkaName: ${stream-connector-config.kafkaName:unavailable}
# Management endpoints
management:
  endpoint:
    restart:
      enabled:  true
  cors:
    allowed-origins: "*"
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: julian
  cloud:
    kubernetes:
      config:
        name: julian
        namespace: colorado
        sources:
          - name: julian
      reload:
        enabled: true
        mode: polling
        period: 2000

stream-connector-config:
  inputTopic: test-01.stream.in
  outputTopic: test-01.stream.out
  errorTopic: test-01.stream.error
  streamSettings:
    application.id: ajar-stream
    client.id: ajar-stream-one
    bootstrap.servers: 172.19.43.2:9092
#    bootstrap.servers: libra:29092

logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG