#Info endpoints
info:
  company: Dexcom
  project: integrations
  kafkaVersion: "${stream-connector-config.kafkaName}"
# Management endpoints
management:
  endpoint:
    restart:
      enabled:  true

spring:
  application:
    name: julian

# Actuator endpoints
endpoints:
  cors:
    allowed-origins: "*"
  metrics:
    enabled: true
  configprops:
    enabled: true
  env:
    enabled: true
  beans:
    enabled: true


