#Info endpoints
info:
  company: Dexcom
  project: integrations
  kafkaVersion: "${stream-connector-config.kafkaName}"
# Management endpoints
management:
  endpoint:
    restart:
      enabled:  true

spring:
  application:
    name: julian

# Actuator endpoints
endpoints:
  cors:
    allowed-origins: "*"
  metrics:
    enabled: true
  configprops:
    enabled: true
  env:
    enabled: true
  beans:
    enabled: true

stream-connector-config:
  inputTopic: test-01.stream.in
  outputTopic: test-01.stream.out
  errorTopic: test-01.stream.error
  kafkaName: ccloud-eu-dev
  streamSettings:
    application.id: ajar-stream
    client.id: ajar-stream-one
    ssl.endpoint.identification.algorithm: https
    sasl.mechanism: PLAIN
    bootstrap.servers: pkc-l5w5g.europe-west3.gcp.confluent.cloud:9092
    sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="LIKDU2ITTTSFTFPP" password="1Qk2A6AJ9aD3OMHYTFwJ96WvyX3ZnpnUvKwwVKqpKsWlkNWq7wV81YQ/JubNt+B2";'
    security.protocol: SASL_SSL
    commit.interval.ms: 10000
    cache.max.bytes.buffering: 0
