#Info endpoints
info:
  company: Dexcom
  project: integrations
  kafkaCluserName: "${stream-connector-config.kafkaCluserName:param-not-available}"
# Management endpoints
management:
  endpoint:
    restart:
      enabled:  true

spring:
  application:
    name: stream-filter
  cloud:
    kubernetes:
      config:
        name: stream-filter
        namespace: big-island
        sources:
          - name: stream-filter
      reload:
        enabled: true
        mode: polling
        period: 2000
# Actuator endpoints
endpoints:
  cors:
    allowed-origins: "*"
  metrics:
    enabled: true
  configprops:
    enabled: true
  env:
    enabled: true
  beans:
    enabled: true

stream-connector-config:
  inputTopic: test-01.stream.in
  outputTopic: test-01.stream.out
  errorTopic: test-01.stream.error
  inputRecordSchema: account-v1.0.2
  streamSettings:
    application.id: ajar-stream
    client.id: ajar-stream-one
    bootstrap.servers: 172.19.43.2:9092
#    bootstrap.servers: libra:29092
