apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: julian-dep
  name: julian-dep
  namespace: colorado
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: julian-dep
  template:
    metadata:
      labels:
        app: julian-dep
    spec:
      containers:
        - image: gcr.io/p8-integrations-eu-dev-2/julian:2a54b33ec9d20be54661f03be98587c288ed76b4
          imagePullPolicy: Always
          name: spring-boot-container
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 30
