apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stream-filter-dep
  name: stream-filter-dep
  namespace: big-island
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: stream-filter-dep
  template:
    metadata:
      labels:
        app: stream-filter-dep
    spec:
      containers:
        - image: gcr.io/p8-integrations-eu-dev-2/stream-filter:latest
          imagePullPolicy: Always
          name: spring-boot-container
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 30
