apiVersion: v1
kind: Service
metadata:
  labels:
    app: julian-dep
  name: julian-svc
  namespace: ramona
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: julian-dep
  sessionAffinity: None
  type: NodePort
