apiVersion: v1
kind: Service
metadata:
  labels:
    app: valley-app-dep
  name: valley-app-svc
  namespace: sorrento
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: valley-app-dep
  sessionAffinity: None
  type: NodePort
