apiVersion: v1
kind: Service
metadata:
  labels:
    app: stream-filter-dep
  name: stream-filter-svc
  namespace: big-island
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: stream-filter-dep
  sessionAffinity: None
  type: NodePort
